version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: dress-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dressdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: dress-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    container_name: dress-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq

volumes:
  mysql-data:


